**User Stories – Sistema ParaBank**

*(Todas as histórias seguem a estrutura: “Como [tipo de usuário], eu quero [objetivo] para [benefício/valor de negócio]”.)*  

| ID | Story | Descrição (detalhada) | Critérios de Aceite (objetivos) |
|----|-------|-----------------------|---------------------------------|
| **US01** | Como **novo usuário**, eu quero **cadastrar minha conta** para poder acessar os serviços bancários online. | O usuário deve ser capaz de preencher um formulário de cadastro contendo campos obrigatórios: nome completo, e‑mail, telefone, CEP, endereço, senha e confirmação de senha. O sistema deve validar a formatação de cada campo (e‑mail válido, telefone no padrão nacional, CEP no formato XXXXX‑XXX). Caso algum campo seja inválido, deve exibir uma mensagem de erro clara ao lado do campo. Quando todos os campos forem válidos, o usuário recebe uma mensagem de “Cadastro concluído com sucesso” e pode prosseguir para o login. | 1. Todos os campos obrigatórios são obrigatórios para submeter o formulário. <br>2. Validação de formato: e‑mail, telefone, CEP. <br>3. Mensagens de erro aparecem ao lado do campo inválido. <br>4. Após cadastro bem‑sucedido, o usuário recebe uma mensagem de confirmação. <br>5. O usuário recém‑cadastro pode usar a mesma e‑mail e senha para acessar o login. |
| **US02** | Como **usuário registrado**, eu quero **fazer login** para acessar minha conta. | O usuário insere seu e‑mail e senha no formulário de login. O sistema verifica as credenciais no banco de dados. Em caso de sucesso, redireciona o usuário para a página inicial da conta (dashboard). Se as credenciais forem inválidas, exibe uma mensagem de erro específica (“E‑mail ou senha inválidos”). | 1. Credenciais válidas levam ao dashboard. <br>2. Credenciais inválidas exibem mensagem de erro. <br>3. O sistema não permite login com campos vazios. <br>4. O usuário pode recuperar a senha (link “Esqueci minha senha”). |
| **US03** | Como **cliente**, eu quero **ver meu saldo atual e o extrato das últimas transações** para acompanhar minha situação financeira. | Depois de logado, o dashboard exibe o saldo corrente da conta em destaque. Abaixo, uma lista de transações recentes (mínimo 10, mais se houver) ordenadas cronologicamente, com data, descrição, valor e saldo pós‑transação. O saldo deve refletir instantaneamente qualquer operação (transferência, pagamento, empréstimo, etc.). | 1. Saldo exibido corretamente e atualizado após cada transação. <br>2. Extrato lista pelo menos 10 transações em ordem cronológica. <br>3. Cada linha do extrato contém data, descrição, valor e saldo pós‑transação. <br>4. O usuário pode clicar em uma transação para ver detalhes completos. |
| **US04** | Como **cliente**, eu quero **transferir fundos entre contas** para gerenciar meu dinheiro. | O usuário acessa a tela de transferência, seleciona a conta de origem (apenas suas contas), conta de destino (pode ser interna ou externa), e insere o valor. O sistema bloqueia transferências cujo valor excede o saldo disponível e exibe uma mensagem “Saldo insuficiente”. Ao confirmar, o valor é debitado da origem, creditado na destino, e a transação é gravada no histórico de ambas as contas. | 1. Campo de valor aceita apenas números positivos. <br>2. Valor > saldo disponível bloqueia operação. <br>3. Operação de transferência atualiza saldo imediatamente em ambas contas. <br>4. Transação aparece no extrato de origem e destino. <br>5. Mensagem de sucesso confirma transferência. |
| **US05** | Como **cliente**, eu quero **solicitar um empréstimo** informando valor e renda anual para que o banco decida aprová‑lo ou negar. | O usuário acessa a tela “Solicitar Empréstimo”, insere valor desejado e sua renda anual. O sistema calcula um índice de aprovação (simplificado) e devolve o status “Aprovado” ou “Negado” imediatamente, exibindo uma mensagem clara com o resultado e eventuais condições (ex.: taxa de juros). | 1. Campos obrigatórios: valor do empréstimo, renda anual. <br>2. Sistema devolve status “Aprovado” ou “Negado” sem atraso. <br>3. Mensagem de resultado inclui informações relevantes (taxa, prazo, se for aprovado). <br>4. Empréstimo aprovado não altera saldo da conta imediatamente (apenas após confirmação). |
| **US06** | Como **cliente**, eu quero **registrar pagamentos de contas** (banco, luz, água, etc.) para manter meu histórico organizado. | O usuário preenche: beneficiário, endereço, cidade, estado, CEP, telefone, conta de destino, valor e data de pagamento (agendamento). Se a data for no futuro, o pagamento fica “pendente” até a data. Ao confirmar, o sistema grava a transação no histórico e, se a data for hoje, debita a conta imediatamente. | 1. Todos os campos obrigatórios são validados quanto ao formato (CEP, telefone). <br>2. Pagamento com data futura fica pendente. <br>3. Pagamento hoje debita conta imediatamente. <br>4. Transação aparece no extrato. <br>5. Mensagem de confirmação inclui detalhes do pagamento. |
| **US07** | Como **qualquer usuário**, eu quero **navegar pelas páginas sem erros** e receber mensagens claras, para garantir uma experiência de uso consistente. | Todos os links, menus e botões devem levar ao destino esperado, sem 404s. Mensagens de erro (validação, falha de rede) são exibidas de forma objetiva e em local visível. Os elementos de navegação (barra superior, menu lateral) são os mesmos em todas as páginas, mantendo a identidade visual. | 1. Navegação entre páginas não gera erros 404 ou 500. <br>2. Mensagens de erro aparecem abaixo do campo ou em modal, com texto claro. <br>3. Layout de navegação (menus, cabeçalho, rodapé) é consistente em todas as telas. <br>4. Navegação funciona em dispositivos desktop e mobile (responsividade). |

---

### Observações de Coerência e Não Sobreposição

* **US01** trata apenas do processo de criação da conta, não tocando na autenticação; *US02* se concentra na verificação das credenciais.  
* **US03** fornece visualização de saldo e extrato, mas não permite nenhuma alteração; *US04* e *US06* são as únicas histórias que alteram o saldo.  
* **US05** lida exclusivamente com a solicitação de empréstimo, enquanto *US04* e *US06* gerenciam transações de transferência e pagamento.  
* **US07** cobre requisitos gerais de navegação, aplicando‑se a todas as outras histórias sem alterar sua lógica de negócio.

Cada story possui critérios de aceite objetivos e mensuráveis, garantindo que sejam testáveis manual ou automaticamente. Os IDs (US01‑US07) fornecem rastreabilidade clara entre requisitos de negócio e implementações futuras.