**User Stories – Sistema ParaBank (versão de demonstração)**  
*(Formato: “Como <tipo de usuário>, eu quero <objetivo> para <benefício>.”)*  

| # | US | Descrição | Critérios de Aceite | Rastreabilidade |
|---|---|-----------|---------------------|-----------------|
| 1 | **US01 – Cadastro de Usuário** | Como *cliente* da ParaBank, eu quero criar uma conta de usuário preenchendo todos os campos obrigatórios para que eu possa começar a usar os serviços bancários online. | • Todos os campos obrigatórios (nome, sobrenome, e‑mail, senha, telefone, CEP, endereço, cidade, estado) são obrigados e não podem ser deixados em branco. <br>• Campos inválidos (telefone em formato não numérico, CEP com letras ou quantidade incorreta de dígitos, e‑mail sem “@” ou domínio inválido) bloqueiam o envio e exibem mensagens de erro claras ao lado do campo. <br>• Ao submeter o formulário com dados válidos, o sistema cria a conta, envia e‑mail de confirmação (simulado) e redireciona para a tela de login. <br>• Se a conta já existir (e‑mail duplicado), exibe mensagem de “E‑mail já cadastrado”. | **US01** |
| 2 | **US02 – Login** | Como *cliente* já registrado, eu quero fazer login na aplicação para acessar meu painel de conta e realizar operações financeiras. | • O usuário digita e‑mail e senha. <br>• Se as credenciais forem válidas, o sistema autentica e redireciona para a página inicial da conta (exibe saldo e menu). <br>• Se as credenciais forem inválidas, exibe “Credenciais inválidas. Tente novamente.” <br>• O login deve ser protegido contra 3 tentativas consecutivas (bloqueio temporário). | **US02** |
| 3 | **US03 – Visualização de Saldo** | Como *cliente*, eu quero visualizar o saldo atual da minha conta para saber quanto dinheiro tenho disponível para usar em transações. | • A tela inicial exibe o saldo atualizado imediatamente após cada operação (depósito, retirada, transferência, pagamento). <br>• O valor exibido é formatado com separador de milhares e duas casas decimais. <br>• Se não houver saldo, exibe “Saldo disponível: R$ 0,00”. | **US03** |
| 4 | **US04 – Visualização de Extrato** | Como *cliente*, eu quero consultar o extrato em ordem cronológica para acompanhar todas as minhas transações recentes e validar a movimentação da conta. | • O extrato mostra as últimas 10 transações (ou todas, se houver menos). <br>• Cada linha exibe data, descrição, tipo (Crédito/Débito), valor e saldo pós‑transação. <br>• O extrato pode ser exportado para PDF (simulação de download). <br>• O usuário pode filtrar por data e tipo de transação. | **US04** |
| 5 | **US05 – Transferência de Fundos** | Como *cliente*, eu quero transferir um valor de uma conta para outra dentro da ParaBank para pagar parceiros ou movimentar recursos. | • O usuário seleciona conta de origem (disponível na lista de contas), conta de destino (qualquer conta válida) e digita o valor. <br>• O sistema valida que o valor é numérico positivo, maior que zero e não excede o saldo disponível da conta de origem. <br>• Se o saldo for insuficiente, exibe “Saldo insuficiente – impossível completar a transferência.” <br>• Ao confirmar, o valor é debitado da origem, creditado na destino, e ambas as contas recebem uma entrada no histórico. <br>• A transação mostra “Transferência concluída com sucesso” e a data/hora. | **US05** |
| 6 | **US06 – Solicitação de Empréstimo** | Como *cliente*, eu quero solicitar um empréstimo informando valor e renda anual para que o sistema avalie a viabilidade do crédito. | • O usuário preenche o valor desejado e a renda anual. <br>• O sistema simula o algoritmo de aprovação (ex.: renda > valor/12 * 0,5) e retorna “Aprovado” ou “Negado” em uma mensagem clara. <br>• Se aprovado, exibe a taxa de juros, prazo e valor mensal calculado. <br>• Se negado, sugere aumentar a renda ou reduzir o valor solicitado. | **US06** |
| 7 | **US07 – Pagamento de Contas** | Como *cliente*, eu quero registrar e agendar pagamentos (beneficiário, endereço, data, valor) para que o débito seja efetuado automaticamente na data escolhida. | • O usuário preenche beneficiário, endereço completo, cidade, estado, CEP, telefone, conta de destino, valor e data de vencimento. <br>• Campos inválidos (CEP com formato incorreto, data no passado) geram mensagens de erro. <br>• Após confirmação, o pagamento aparece no histórico de transações como “Agendado”. <br>• Na data de vencimento, a transação é processada automaticamente e o usuário recebe notificação. | **US07** |
| 8 | **US08 – Navegação e Usabilidade** | Como *cliente*, eu quero que todas as páginas da ParaBank carreguem sem erros de navegação, exibindo mensagens de erro claras e mantendo a consistência visual, para ter uma experiência fluida e confiável. | • Todas as rotas (login, cadastro, painel, extrato, transferências, empréstimos, pagamentos) carregam em ≤ 2 segundos. <br>• Erros de carregamento mostram “Ocorreu um problema. Por favor, recarregue a página.” <br>• Todos os menus, ícones e links são consistentes e responsivos em desktop e dispositivos móveis. <br>• Mensagens de erro (formulários, transações, login) são exibidas em destaque próximo ao campo ou modal. | **US08** |

---

### Observações de Coerência e Não‑Sobreposição  
- **US01** cobre somente o fluxo de criação de conta; não inclui validações de login.  
- **US02** trata apenas da autenticação, sem interações de cadastro.  
- **US03** e **US04** são independentes: saldo imediato e extrato histórico.  
- **US05** foca apenas em transferências internas (de uma conta para outra na ParaBank).  
- **US06** e **US07** tratam de operações distintas (empréstimo e pagamento), cada uma com seus próprios campos e regras.  
- **US08** abrange requisitos transversais de navegação e usabilidade, garantindo que não haja dependência direta das demais histórias, mas que sirva como base de qualidade para todas elas.

Essas User Stories formam um conjunto completo, testável e alinhado ao escopo do documento de Critérios de Aceite do ParaBank.